# Generated by Django 5.0.6 on 2024-06-06 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_group_room_alter_room_owner'),
        ('users', '0005_customuser_room_subuser_groups_subuser_room_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='subusers',
            field=models.ManyToManyField(related_name='sub_users_in_group', to='users.subuser'),
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='users_in_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='subusers',
            field=models.ManyToManyField(related_name='sub_users_in_room', to='users.subuser'),
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(related_name='users_in_room', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ActivityClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(related_name='groups_in_activity_class', to='rooms.group')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_class_in_room', to='rooms.room')),
                ('subusers', models.ManyToManyField(related_name='sub_users_in_activity_group', to='users.subuser')),
                ('users', models.ManyToManyField(related_name='users_in_activity_class', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
