# Generated by Django 4.2.6 on 2024-06-06 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_remove_customuser_room_remove_subuser_groups_and_more'),
        ('rooms', '0005_alter_activityclass_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityclass',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='groups_in_activity_class', to='rooms.group'),
        ),
        migrations.AlterField(
            model_name='activityclass',
            name='subusers',
            field=models.ManyToManyField(blank=True, related_name='sub_users_in_activity_group', to='users.subuser'),
        ),
        migrations.AlterField(
            model_name='activityclass',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users_in_activity_class', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='subusers',
            field=models.ManyToManyField(blank=True, related_name='sub_users_in_group', to='users.subuser'),
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users_in_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
