# Generated by Django 5.0.6 on 2024-06-10 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_statute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='trainers',
            field=models.ManyToManyField(related_name='trainer_in_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
