# Generated by Django 5.0.6 on 2024-06-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_alter_statute_room_statuteacceptance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statuteacceptance',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='statuteacceptance',
            name='accepted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
