# Generated by Django 5.0.6 on 2024-06-11 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_remove_statuteacceptance_is_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_code', to='rooms.room'),
        ),
    ]
