# Generated by Django 5.0.6 on 2024-06-11 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_alter_invitationcode_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityClass',
        ),
    ]
