# Generated by Django 5.0.6 on 2024-06-18 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0016_alter_room_trainers'),
        ('users', '0008_remove_customuser_is_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='subusers',
            field=models.ManyToManyField(blank=True, null=True, related_name='sub_users_in_room', to='users.subuser'),
        ),
        migrations.AlterField(
            model_name='room',
            name='unaccepted_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='unaccepted_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_in_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
