# Generated by Django 5.0.6 on 2024-06-11 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0013_delete_activityclass'),
        ('users', '0006_remove_customuser_room_remove_subuser_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(blank=True, related_name='groups_in_activity_class', to='rooms.group')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_class_in_room', to='rooms.room')),
                ('subusers', models.ManyToManyField(blank=True, related_name='sub_users_in_activity_group', to='users.subuser')),
                ('users', models.ManyToManyField(blank=True, related_name='users_in_activity_class', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
