# Generated by Django 5.0.6 on 2024-06-11 10:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_class', '0002_activityclass_cost_balanceforactivityclass'),
        ('rooms', '0013_delete_activityclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceforactivityclass',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='balanceforactivityclass',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='balanceforactivityclass',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balanceforactivityclass',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='balanceforactivityclass',
            name='activity_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_in_balance', to='activity_class.activityclass'),
        ),
        migrations.AlterField(
            model_name='balanceforactivityclass',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_in_balance', to='rooms.room'),
        ),
    ]
