# Generated by Django 5.0.6 on 2024-06-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_class', '0003_balanceforactivityclass_amount_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityclass',
            name='time',
            field=models.DurationField(null=True),
        ),
    ]
