# Generated by Django 5.0.6 on 2024-06-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_class', '0004_activityclass_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanceforactivityclass',
            name='amount_due',
        ),
        migrations.AddField(
            model_name='activityclass',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='activityclass',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
