# Generated by Django 4.2.6 on 2024-06-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_class', '0006_balanceforactivityclass_amount_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceforactivityclass',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
