# Generated by Django 4.2.6 on 2024-06-12 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_room_remove_subuser_groups_and_more'),
        ('activity_class', '0007_alter_balanceforactivityclass_amount_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceforactivityclass',
            name='subuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_subuser', to='users.subuser'),
        ),
    ]
