# Generated by Django 4.2.6 on 2024-06-12 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_class', '0008_balanceforactivityclass_subuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceforactivityclass',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
