# Generated by Django 5.0.6 on 2024-06-14 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_class', '0009_alter_balanceforactivityclass_user'),
        ('rooms', '0013_delete_activityclass'),
        ('users', '0007_alter_customuser_is_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityclass',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups_in_activity_class', to='rooms.group'),
        ),
        migrations.AlterField(
            model_name='activityclass',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_class_in_room', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='activityclass',
            name='subusers',
            field=models.ManyToManyField(blank=True, null=True, related_name='sub_users_in_activity_group', to='users.subuser'),
        ),
        migrations.AlterField(
            model_name='activityclass',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_in_activity_class', to=settings.AUTH_USER_MODEL),
        ),
    ]
