# Generated by Django 5.0.6 on 2024-06-26 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_class', '0011_alter_activityclass_groups_alter_activityclass_room_and_more'),
        ('rooms', '0017_alter_room_subusers_alter_room_unaccepted_users_and_more'),
        ('users', '0008_remove_customuser_is_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('activity_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attendance_activity', to='activity_class.activityclass')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_in_attendance', to='rooms.room')),
                ('subuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subuser_attendance', to='users.subuser')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_attendance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
