# Generated by Django 5.0.6 on 2024-08-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_class', '0012_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='confirmation_present',
            field=models.BooleanField(default=False),
        ),
    ]
