# Generated by Django 5.0.6 on 2024-08-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_class', '0013_attendance_confirmation_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityclass',
            name='end_date',
        ),
        migrations.AddField(
            model_name='activityclass',
            name='localization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activityclass',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
