# Generated by Django 5.0.6 on 2024-08-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_class', '0014_remove_activityclass_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityclass',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
