# Generated by Django 5.0.6 on 2024-06-03 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tempmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempModel',
        ),
    ]
