# Generated by Django 5.0.6 on 2024-06-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_group_room_alter_room_owner'),
        ('users', '0004_subuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='room',
            field=models.ManyToManyField(related_name='users_in_room', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='subuser',
            name='groups',
            field=models.ManyToManyField(related_name='sub_users_in_group', to='rooms.group'),
        ),
        migrations.AddField(
            model_name='subuser',
            name='room',
            field=models.ManyToManyField(related_name='sub_users_in_room', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(related_name='users_in_group', to='rooms.group'),
        ),
    ]
