# Generated by Django 5.0.6 on 2024-06-16 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_is_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_trainer',
        ),
    ]
