# Generated by Django 5.0.6 on 2024-08-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_managers_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='subuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
