# Generated by Django 5.0.6 on 2024-08-13 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_subuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
