# Generated by Django 5.0.6 on 2024-08-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='logo_img',
            field=models.ImageField(null=True, upload_to='logo_user/'),
        ),
        migrations.AddField(
            model_name='subuser',
            name='logo_img',
            field=models.ImageField(null=True, upload_to='logo_user/'),
        ),
    ]
