# Generated by Django 5.0.6 on 2024-08-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_logo_img_subuser_logo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subuser',
            name='logo_img',
            field=models.ImageField(null=True, upload_to='logo_subuser/'),
        ),
    ]
